# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      editorVersion:
        default: '2021.2.12f1'
      logFile:
        default: '/Users/aaron/workspace/AppBuilder/Editor.log'
      executeMethod:
        default: 'AppBuilderSample.BasicAndroid.Build'
      buildTarget:
        default: 'Android'
      projectPath:
        default: '/Users/aaron/workspace/AppBuilder'
      appsettings:
        default: 'Assets/Samples/AppBuilder/0.0.1/Basic Android'
      keystore:
        default: 'Assets/Samples/AppBuilder/0.0.1/Basic Android/user.keystore'
      keystorePasswd:
        default: '111111'
      keystoreAlias:
        default: 'appbuilder'
      keystoreAliasPasswd:
        default: '111111'
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: EditorPath
      run: echo "run $UNITY_EDITORS/${{github.event.inputs.editorVersion}}/Unity.app/Contents/MacOS/Unity"
    - name: Build
      run: >
        $UNITY_EDITORS/${{github.event.inputs.editorVersion}}/Unity.app/Contents/MacOS/Unity
        -batchmode 
        -quit 
        -logFile "${{github.event.inputs.logFile}}" 
        -executeMethod "${{github.event.inputs.executeMethod}}" 
        -buildTarget "${{github.event.inputs.buildTarget}}" 
        -projectPath "${{github.event.inputs.projectPath}}" 
        -appsettings "${{github.event.inputs.appsettings}}" 
        -keystore "${{github.event.inputs.keystore}}" 
        -keystorePasswd "${{github.event.inputs.keystorePasswd}}" 
        -keystoreAlias "${{github.event.inputs.keystoreAlias}}" 
        -keystoreAliasPasswd "${{github.event.inputs.keystoreAliasPasswd}}"
    - name: Upload
      uses: actions/upload-artifact@v3.0.0
      with:
        path: ${{github.event.inputs.projectPath}}/Build/${{github.event.inputs.buildTarget}}/AppBuilder.apk
